apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-pod-autocomplete-sa
  namespace: kube-pod-autocomplete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-pod-autocomplete-clusterrole
  namespace: kube-pod-autocomplete
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-pod-autocomplete-clusterrolebinding
  namespace: kube-pod-autocomplete
subjects:
- kind: ServiceAccount
  name: kube-pod-autocomplete-sa
  namespace: kube-pod-autocomplete
roleRef:
  kind: ClusterRole
  name: kube-pod-autocomplete-clusterrole
  apiGroup: rbac.authorization.k8s.io
