namespace: kube-pod-autocomplete

name: kube-pod-autocomplete
replicas: 1
containerPort: 8080

service:
  name: kube-pod-autocomplete-service
  type: ClusterIP
  servicePort: 8080
  externalPort: 8080

serviceAccount:
  name: kube-pod-autocomplete-sa

ingress:
  enabled: false

rbac:
  clusterRoleName: kube-pod-autocomplete-clusterrole
  resourceTypes:
    - "pods"
  clusterRoleBindingName: kube-pod-autocomplete-clusterrolebinding

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
