name: Artifacts

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish artifacts'
        required: true
        default: false
        type: boolean
    outputs:
      container-image-tag:
        description: Container image tag
        value: ${{ jobs.container-image.outputs.tag }}
jobs:
  container-image:
    name: Container-Image
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gather build metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest = false
          tags: |
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ inputs.publish }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        if: ${{ inputs.publish == false }}
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=image.tar

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: ${{ inputs.publish == true }}
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,push=true
      
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kube-Pod-Autocomplete Image
          path: image.tar

  helm-chart:
    name: Helm-Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm lint
        run: make lint-helm

      - name: Helm package
        run: make helm-chart

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kube-Pod-Autocomplete Helm-Chart
          path: build/*.tgz
